spring:
  datasource:
    username: postgres
    password: gateway123
    url: jdbc:postgresql://localhost:5432/GATEWAY_DB

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: certificatefatec@gmail.com
    password: bebedanca
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      location: "./certs"

root-user:
  initialize: false
  custom-password: true
  details:
    email: "root@root.com"
    name: "root"
    password: "test"

jwt:
  secret: "TH3GAT3WaY" #ideal seria um config server
  expiration-minutes: 120


