spring:
  datasource:
    username: postgres
    password: gateway123
    url: jdbc:postgresql://localhost:5432/GATEWAY_DB

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    show-sql: true

root-user:
  initialize: true
  details:
    email: "root@root.com"
    name: "root"

jwt:
  secret: "TH3GAT3WaY" #ideal seria um config server
  expiration-minutes: 120