version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: GATEWAY_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gateway123
    ports:
      - "5432:5432"