CREATE TABLE LOCATION (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    LOCATION_TYPE VARCHAR(50) NOT NULL,
    LOCATION_PARAMETERS JSONB NOT NULL,
    dat_creation TIMESTAMP NOT NULL,
    dat_update TIMESTAMP NOT NULL
);

CREATE TABLE EVENT (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    event_name VARCHAR(100) NOT NULL,
    event_owner_code UUID NOT NULL,
    event_description TEXT NOT NULL,
    dat_creation TIMESTAMP NOT NULL,
    dat_update TIMESTAMP NOT NULL,
    location_id BIGINT,
    FOREIGN KEY (location_id) REFERENCES LOCATION(id)
);

CREATE TABLE USER_EVENT (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    USER_ID BIGINT NOT NULL,
    EVENT_ID BIGINT NOT NULL,
    dat_check_in TIMESTAMP NOT NULL,
    dat_check_out TIMESTAMP NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(id),
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(id)
);
